### ISSUE TITLE
bug: receiving compile error on Ubuntu 19.10

### ISSUE THREAD

**Issue by jackson-elfers** [stockmarkat/stockmarket-simulation#151]
## Expected Behavior
Should compile.

## Actual Behavior
Doesn't compile.

## Steps to Reproduce the Problem

```
yarn install
yarn start
```
## Error Message
```
/stockmarket-simulation/node_modules/@types/enzyme/index.d.ts
(70,20): Generic type 'ReactElement<P>' requires 1 type argument(s).
```

## Specifications
  - Platform: Ubuntu 19.10
  - Subsystem: ?

**Comment by panmona** [comment]
Thanks for reporting the issue. I can reproduce the problem on my local system.
@RohrerF Could you take a look on how we can solve this?

**Comment by RohrerF** [comment]
latest master should work now. I have updated a couple of packages which resolved the problem 😃
