### ISSUE TITLE
CapitalDevelopmentChart not updating automaticly

### ISSUE THREAD

**Issue by RohrerF** [stockmarkat/stockmarket-simulation#56]
## Expected Behavior
The chart updates if you stay on the site

## Actual Behavior
it only refreshes after you switch the page and switch back

**Comment by panmona** [comment]
is this a store or ui issue?

**Comment by RohrerF** [comment]
in the store it's set correctly

**Comment by panmona** [comment]
Huh. Sure? 
Because it's done exactly the same as the stock card / it's the same chart.

Haven't spotted the root cause yet
