### ISSUE TITLE
Build a "bank balance tile" component

### ISSUE THREAD

**Issue by panmona** [stockmarkat/stockmarket-simulation#7]
It should look a bit like this:
![image](https://user-images.githubusercontent.com/16801528/38919611-4d6b5b64-42f1-11e8-8402-5ddcc51f7986.png)

@lpzimmermann: I need to show you how to use Storybook so it will be easier to build this.

**Comment by RohrerF** [comment]
Don't forget css stuff from the template. I haven't set this up yet.

**Comment by lpzimmermann** [comment]
@maracuja-juice das Schwein oder Cash Symbol dynamisch, also Klass wo über Perops gsetzt wird, oder eifach eis einzigs (also e hardcodeti css Klass) vlt wottmer ja die TIle no für anders verwende mit entsprechend anderne symbol? (Ich weiss du cheggsch die Frag nöd aber du heissisch au nöd Tennis)

haha Mailbox vollspamme

**Comment by panmona** [comment]
@lpzimmermann Es git verschiedeni Chärtli. 
Mer bruuched eis generells und dänn das da mitem Schwein wür vom generelle Ableite.

**Comment by RohrerF** [comment]
Props werded so was i die richtig sii

- Name (im Mockuo Konto)
- Icon (string name von icon)
- value (als string das au % möglich sind)
